# model setting
wavelet: morlet
max_scale: 3
nb_orients: 2
depth: 3
normalize_wavelets: true

# others
full_inverse: true

optimizations:
  mixed_precision: false
  force_float16: false
  disk_cache: false
