# model setting
wavelet: meyer
max_scale: 2
nb_orients: 3
depth: 2
normalize_wavelets: false

# others
full_inverse: false

optimizations:
  mixed_precision: false
  force_float16: true
  disk_cache: false
